name: CheckThrow
version: '${project.version}'
main: me.rang.checkthrow.checkthrow.CheckThrow
api-version: 1.19
authors: [ lnxdx ]
description: check drop
commands:
  qtoggle:
    description: qtoggle 활성화/비활성화
